// MeterMatch — client-side PDF export for findings.
// Dependency-free: opens a print-optimized report in a new window and triggers
// the browser's native "Save as PDF". Works everywhere, nothing to install.

import type { Finding } from "./engine";
import { usd2 } from "./format";

export interface PdfMeta {
  period?: string; // e.g. "2026-05" or "Uploaded"
  source?: string; // e.g. "AWS live", "CSV upload"
}

function esc(s: unknown): string {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

export function exportFindingsPdf(findings: Finding[], meta: PdfMeta = {}): void {
  if (typeof window === "undefined" || findings.length === 0) return;

  const rows = [...findings].sort((a, b) => b.annualRecoverable - a.annualRecoverable);
  const totalAnnual = rows.reduce((s, f) => s + f.annualRecoverable, 0);
  const totalMonthly = rows.reduce((s, f) => s + f.monthlyRecoverable, 0);
  const accounts = new Set(rows.map((f) => f.accountId)).size;
  const generated = new Date().toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" });

  const sevColor: Record<string, string> = {
    critical: "#dc2626",
    high: "#ea580c",
    medium: "#ca8a04",
    low: "#0891b2",
  };

  const tableRows = rows
    .map(
      (f) => `
      <tr>
        <td>${esc(f.accountName)}</td>
        <td>${esc(f.title)}</td>
        <td><span class="sev" style="color:${sevColor[f.severity] ?? "#475569"}">●</span> ${esc(f.severity)}</td>
        <td class="num">${usd2(f.expected)}</td>
        <td class="num">${usd2(f.billed)}</td>
        <td class="num strong">${usd2(f.annualRecoverable)}</td>
      </tr>`
    )
    .join("");

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>MeterMatch — Revenue Leakage Report</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
         color: #0f172a; margin: 0; padding: 40px; }
  .brand { font-size: 12px; letter-spacing: .14em; color: #6366f1; font-weight: 700; }
  h1 { font-size: 24px; margin: 6px 0 2px; }
  .meta { color: #64748b; font-size: 12px; }
  .cards { display: flex; gap: 14px; margin: 24px 0 8px; }
  .card { flex: 1; border: 1px solid #e2e8f0; border-radius: 10px; padding: 14px 16px; }
  .card .label { font-size: 11px; color: #64748b; text-transform: uppercase; letter-spacing: .04em; }
  .card .value { font-size: 22px; font-weight: 700; margin-top: 4px; }
  .card .value.accent { color: #059669; }
  table { width: 100%; border-collapse: collapse; margin-top: 22px; font-size: 12px; }
  thead th { text-align: left; color: #64748b; font-size: 10px; letter-spacing: .06em;
             text-transform: uppercase; border-bottom: 2px solid #e2e8f0; padding: 8px 10px; }
  tbody td { padding: 9px 10px; border-bottom: 1px solid #f1f5f9; }
  td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
  td.strong { font-weight: 700; color: #059669; }
  .sev { font-size: 9px; vertical-align: middle; }
  tfoot td { padding: 12px 10px; font-weight: 700; border-top: 2px solid #e2e8f0; }
  .footer { margin-top: 28px; color: #94a3b8; font-size: 10px; }
  @media print { body { padding: 24px; } @page { margin: 16mm; } }
</style>
</head>
<body>
  <div class="brand">METERMATCH</div>
  <h1>Revenue Leakage Report</h1>
  <div class="meta">
    Period: ${esc(meta.period ?? "—")}${meta.source ? " · Source: " + esc(meta.source) : ""} · Generated ${esc(generated)}
  </div>

  <div class="cards">
    <div class="card"><div class="label">Findings</div><div class="value">${rows.length}</div></div>
    <div class="card"><div class="label">Accounts affected</div><div class="value">${accounts}</div></div>
    <div class="card"><div class="label">Monthly recoverable</div><div class="value">${usd2(totalMonthly)}</div></div>
    <div class="card"><div class="label">Annual recoverable</div><div class="value accent">${usd2(totalAnnual)}</div></div>
  </div>

  <table>
    <thead>
      <tr>
        <th>Account</th><th>Leakage type</th><th>Severity</th>
        <th class="num">Expected</th><th class="num">Billed</th><th class="num">Annual recoverable</th>
      </tr>
    </thead>
    <tbody>${tableRows}</tbody>
    <tfoot>
      <tr><td colspan="5">Total annual recoverable</td><td class="num strong">${usd2(totalAnnual)}</td></tr>
    </tfoot>
  </table>

  <div class="footer">Generated by MeterMatch · Figures are estimates based on the reconciliation engine and the data provided.</div>
  <script>window.onload = function () { window.print(); };</script>
</body>
</html>`;

  const w = window.open("", "_blank");
  if (!w) {
    alert("Please allow pop-ups to export the PDF report.");
    return;
  }
  w.document.open();
  w.document.write(html);
  w.document.close();
}
